version: "3.8"

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev